services:
  # Backend service
  backend:
    build:
      context: .
      dockerfile: deployment/docker/backend.Dockerfile
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - backend/.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: deployment/docker/frontend.Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - frontend/.env
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    restart: unless-stopped

  # Database service
  db:
    image: postgres:13-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped

volumes:
  postgres_data: