"""Create detection table

Revision ID: 6d1d7f55d803
Revises: 
Create Date: 2025-05-05 23:16:12.092945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1d7f55d803'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('num_detections', sa.Integer(), nullable=True),
    sa.Column('ppe_detected', sa.Boolean(), nullable=True),
    sa.Column('violations_detected', sa.Boolean(), nullable=True),
    sa.Column('detection_results', sa.JSON(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_image_id'), 'detections', ['image_id'], unique=False)
    op.create_index(op.f('ix_detections_source_id'), 'detections', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_source_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_image_id'), table_name='detections')
    op.drop_table('detections')
    # ### end Alembic commands ###
